-- NinjaTrader 8 account mirror.
--
-- A NinjaScript AddOn running inside NT8 pushes account values, fills,
-- positions and closed trades to /api/trading/events, which writes them here.
-- Nothing in this schema is ever written from the browser: the panel reads it
-- through the service-role key, so RLS stays enabled with no policies.
--
-- Prefix follows the rest of the project (nexus_), scoped with nt_ so it is
-- obvious the rows come from NinjaTrader rather than from the web agent.

-- ── Accounts ─────────────────────────────────────────────────────────────────
-- One row per NT8 account. The AddOn upserts the whole row on every account
-- item change, so this table is a live mirror rather than a history.

create table if not exists public.nexus_nt_accounts (
  name             text primary key,
  connection       text,
  denomination     text,
  cash_value       numeric(20, 2),
  realized_pnl     numeric(20, 2),
  unrealized_pnl   numeric(20, 2),
  gross_realized   numeric(20, 2),
  buying_power     numeric(20, 2),
  net_liquidation  numeric(20, 2),
  reported_at      timestamptz not null,
  updated_at       timestamptz not null default now()
);

-- ── Executions (fills) ───────────────────────────────────────────────────────
-- id is NT8's own execution id, so a replayed or retried batch is idempotent.

create table if not exists public.nexus_nt_executions (
  id              text primary key,
  account         text        not null,
  instrument      text        not null,
  order_action    text,
  market_position text,
  quantity        integer     not null,
  price           numeric(20, 8) not null,
  commission      numeric(20, 4),
  order_id        text,
  executed_at     timestamptz not null,
  received_at     timestamptz not null default now()
);

create index if not exists nexus_nt_executions_account_time_idx
  on public.nexus_nt_executions (account, executed_at desc);

create index if not exists nexus_nt_executions_instrument_idx
  on public.nexus_nt_executions (instrument, executed_at desc);

-- ── Open positions ───────────────────────────────────────────────────────────
-- Live state, one row per account+instrument. A flat position is deleted by
-- the ingest route rather than kept with quantity 0, so this table only ever
-- holds what is actually open right now.

create table if not exists public.nexus_nt_positions (
  account         text        not null,
  instrument      text        not null,
  market_position text        not null,
  quantity        integer     not null,
  average_price   numeric(20, 8) not null,
  unrealized_pnl  numeric(20, 2),
  opened_at       timestamptz,
  reported_at     timestamptz not null,
  updated_at      timestamptz not null default now(),
  primary key (account, instrument)
);

-- ── Closed trades ────────────────────────────────────────────────────────────
-- NT8's Account class exposes no Trades collection, so the AddOn pairs fills
-- itself and emits one row when a position returns to flat. id is generated by
-- the AddOn from account+instrument+exit time, which keeps retries idempotent.

create table if not exists public.nexus_nt_trades (
  id            text primary key,
  account       text        not null,
  instrument    text        not null,
  direction     text        not null check (direction in ('Long', 'Short')),
  quantity      integer     not null,
  entry_price   numeric(20, 8) not null,
  exit_price    numeric(20, 8) not null,
  point_value   numeric(20, 4),
  pnl_points    numeric(20, 8),
  pnl_currency  numeric(20, 2),
  commission    numeric(20, 4),
  entry_at      timestamptz not null,
  exit_at       timestamptz not null,
  received_at   timestamptz not null default now()
);

create index if not exists nexus_nt_trades_account_exit_idx
  on public.nexus_nt_trades (account, exit_at desc);

-- ── updated_at maintenance ───────────────────────────────────────────────────
-- Reuses the trigger function created in 0001.

drop trigger if exists nexus_nt_accounts_touch on public.nexus_nt_accounts;
create trigger nexus_nt_accounts_touch
  before update on public.nexus_nt_accounts
  for each row execute function public.nexus_touch_updated_at();

drop trigger if exists nexus_nt_positions_touch on public.nexus_nt_positions;
create trigger nexus_nt_positions_touch
  before update on public.nexus_nt_positions
  for each row execute function public.nexus_touch_updated_at();

-- ── RLS: deny by default ─────────────────────────────────────────────────────

alter table public.nexus_nt_accounts   enable row level security;
alter table public.nexus_nt_executions enable row level security;
alter table public.nexus_nt_positions  enable row level security;
alter table public.nexus_nt_trades     enable row level security;
